version: '3.2'
services:
  my_app:
    image: gptslides 
    volumes:
      - uploads_volume:/path/in/container/uploads
      - split_uploads_volume:/path/in/container/split_uploads
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500m  
volumes:
  uploads_volume:
  split_uploads_volume:
